### ISSUE TITLE
Query schema can't be changed from the UI

### ISSUE THREAD

**Issue by MiroCillik** [keboola/db-extractor-mysql#27] opened 2017-12-18 12:24 UTC
Let's have a simple query config:
```
{
	"enabled": true,
	"name": "quantitative_unit",
	"incremental": true,
	"outputTable": "in.c-keboola-ex-db-mysql.quantitative-unit",
	"table": {
		"schema": "erp-reporting",
		"tableName": "quantitative_unit"
	},
	"columns": [],
	"primaryKey": ["id"],
	"id": 7323
}
```

The `schema` field is not editable in the UI and when I change the DB credentials to different database name, the schema in the query config remains the same causing an error.
https://keboola.zendesk.com/agent/tickets/7697

Where's the schema field coming from anyways? It is from the credentials? If so, all the queries needs to be updated on credentials change. Or it should be editable in the query configuration UI.

**Comment by pivnicek** [comment] 2017-12-18 12:30
So, the schema comes from which table you select in the dropdown.
So if you change the the database in the credentials it may not have access to the table you selected before.  There will be an appropriate error message regarding this, and the form should show it as invalid.  

It is fixed by re-selecting the table.

btw, if you leave the `database` field empty in the credentials you'll have access to all schemas/tables.

**Comment by pivnicek** [comment] 2017-12-18 12:31
duplicate of: https://github.com/keboola/db-extractor-mysql/issues/22
but maybe pre-maturely closed?

**Comment by MiroCillik** [comment] 2017-12-18 12:45
Ah, I see. It's kinda confusing, because you don't see the schema field in the UI.
Maybe display the schema in the UI in a non-editable field. The error message should say, that user have to reselect the table. Something like:
```
The table schema "erp-reporting" is different from the connection database "erp". Change or omit the database name in credentials or select table from schema "erp" in your query ${query}.
```

And in the dropdown, where you're selecting the tables, there should also be schema(s). What if I omit the database name in the credentials and have 2 tables with same name in different schemas?

**Comment by pivnicek** [comment] 2017-12-18 12:52
There is schema already in the dropdown:

![image](https://user-images.githubusercontent.com/569139/34106938-7cdec72e-e3fa-11e7-85e8-61a016c4532b.png)

I'll think about prefixing the table.name with the schema when selected.

**Comment by pivnicek** [comment] 2017-12-18 12:56
But this shouldn't be so confusing, you're correct, I'll simplify it somehow.  Thanks for raising the issue.

**Comment by MiroCillik** [comment] 2017-12-18 12:57
Ahh, OK, didn't scroll to the very top :) 
Yeah, maybe just explain it more in the error message, or prefix the selected Source Table with non-editable schema name..

**Comment by RevoltBI** [comment] 2017-12-18 15:59
Guys I have a configured extractor with over 50 tables, I need to port it vanilla from one database on another. I hope that you are not considering solving this issue by saying that the user need to click on every single table and change its location :-) I just need to switch the db from one to another.

**Comment by pivnicek** [comment] 2017-12-18 16:03
@RevoltBI In that case we can update the configuration via the API. https://keboola.docs.apiary.io/#reference/component-configurations/manage-configurations/update-configuration

**Comment by RevoltBI** [comment] 2017-12-18 16:07
Yes thank you :-) 

But I think you should do the schema editable. Imagine that I am a tech savy business user for whom just applying the credentials to the database is a supreme technical feat. Updating the schema via API is already half an hour spent into reading the documentation for me imagine  now a nontechnical user...

**Comment by pivnicek** [comment] 2017-12-18 16:14
agreed, this is the second time that this database change issue has come up, so it's definitely a problem we need to solve.  
I think it should be possible to "know" that the configuration is not valid after a database change and either update it automatically (which may not work if the schemas don't have the same tables), or prompt the user to update in a 1-click way.

will try to get something out for this this week.
Cheers @RevoltBI !

**Comment by pivnicek** [comment] 2017-12-18 16:25
Since this is a UI issue (imho), I've moved it to https://github.com/keboola/kbc-ui/issues/1385

**Closed** 2019-01-30 20:08 UTC
